version = 3.11.5

runner.dialect = scala213source3

project.git = true

maxColumn = 120
trailingCommas = always

preset = default
align.preset = none

indent {
  defnSite = 2
  extendSite = 0
}

spaces {
  inInterpolatedStringCurlyBraces = true
}

newlines {
  source = keep
  implicitParamListModifierForce = [after]
  avoidForSimpleOverflow = [
    tooLong,
    slc,
  ]
}

verticalMultiline {
  atDefnSite = true
  arityThreshold = 4
  newlineAfterOpenParen = true
}

danglingParentheses.exclude = []

docstrings {
  wrapMaxColumn = 100
  style = Asterisk
  oneline = unfold
  blankFirstLine = unfold
}

rewrite.rules = [
  Imports,
  RedundantParens,
  SortModifiers,
  prefercurlyfors,
]

rewrite.sortModifiers.preset = styleGuide

rewrite.imports {
  sort = ascii
  groups = [
    [".*"],
    ["java\\..*", "javax\\..*", "scala\\..*"],
  ]
}
